/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait AccountsApi: Send + Sync {
    /// POST /accounts/create
    ///
    ///
    async fn create_account_accounts_create_post<'add_account_schema>(
        &self,
        add_account_schema: models::AddAccountSchema,
    ) -> Result<models::ResponseSchema, Error<CreateAccountAccountsCreatePostError>>;

    /// GET /accounts/{account}
    ///
    /// Retrieve the details of a character.
    async fn get_account_accounts_account_get<'account>(
        &self,
        account: &'account str,
    ) -> Result<models::AccountDetailsSchema, Error<GetAccountAccountsAccountGetError>>;

    /// GET /accounts/{account}/achievements
    ///
    /// Retrieve the achievements of a account.
    async fn get_account_achievements_accounts_account_achievements_get<
        'account,
        'r_type,
        'completed,
        'page,
        'size,
    >(
        &self,
        account: &'account str,
        r#type: Option<&'r_type str>,
        completed: Option<bool>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<
        models::DataPageAccountAchievementSchema,
        Error<GetAccountAchievementsAccountsAccountAchievementsGetError>,
    >;
}

pub struct AccountsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AccountsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl AccountsApi for AccountsApiClient {
    async fn create_account_accounts_create_post<'add_account_schema>(
        &self,
        add_account_schema: models::AddAccountSchema,
    ) -> Result<models::ResponseSchema, Error<CreateAccountAccountsCreatePostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/accounts/create", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&add_account_schema);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ResponseSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ResponseSchema`")))),
            }
        } else {
            let local_var_entity: Option<CreateAccountAccountsCreatePostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve the details of a character.
    async fn get_account_accounts_account_get<'account>(
        &self,
        account: &'account str,
    ) -> Result<models::AccountDetailsSchema, Error<GetAccountAccountsAccountGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/{account}",
            local_var_configuration.base_path,
            account = crate::apis::urlencode(account)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccountDetailsSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AccountDetailsSchema`")))),
            }
        } else {
            let local_var_entity: Option<GetAccountAccountsAccountGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve the achievements of a account.
    async fn get_account_achievements_accounts_account_achievements_get<
        'account,
        'r_type,
        'completed,
        'page,
        'size,
    >(
        &self,
        account: &'account str,
        r#type: Option<&'r_type str>,
        completed: Option<bool>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<
        models::DataPageAccountAchievementSchema,
        Error<GetAccountAchievementsAccountsAccountAchievementsGetError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/accounts/{account}/achievements",
            local_var_configuration.base_path,
            account = crate::apis::urlencode(account)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = r#type {
            local_var_req_builder =
                local_var_req_builder.query(&[("type", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = completed {
            local_var_req_builder =
                local_var_req_builder.query(&[("completed", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = size {
            local_var_req_builder =
                local_var_req_builder.query(&[("size", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageAccountAchievementSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DataPageAccountAchievementSchema`")))),
            }
        } else {
            let local_var_entity: Option<
                GetAccountAchievementsAccountsAccountAchievementsGetError,
            > = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`create_account_accounts_create_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAccountAccountsCreatePostError {
    Status456(),
    Status457(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_account_accounts_account_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAccountAccountsAccountGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_account_achievements_accounts_account_achievements_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAccountAchievementsAccountsAccountAchievementsGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}
