/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait GrandExchangeApi: Send + Sync {
    /// GET /grandexchange/history/{code}
    ///
    /// Fetch the sales history of the item for the last 7 days.
    async fn get_ge_sell_history_grandexchange_history_code_get<
        'code,
        'seller,
        'buyer,
        'page,
        'size,
    >(
        &self,
        code: &'code str,
        seller: Option<&'seller str>,
        buyer: Option<&'buyer str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<
        models::DataPageGeOrderHistorySchema,
        Error<GetGeSellHistoryGrandexchangeHistoryCodeGetError>,
    >;

    /// GET /grandexchange/orders/{id}
    ///
    /// Retrieve the sell order of a item.
    async fn get_ge_sell_order_grandexchange_orders_id_get<'id>(
        &self,
        id: &'id str,
    ) -> Result<models::GeOrderReponseSchema, Error<GetGeSellOrderGrandexchangeOrdersIdGetError>>;

    /// GET /grandexchange/orders
    ///
    /// Fetch all sell orders.
    async fn get_ge_sell_orders_grandexchange_orders_get<'code, 'seller, 'page, 'size>(
        &self,
        code: Option<&'code str>,
        seller: Option<&'seller str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<models::DataPageGeOrderSchema, Error<GetGeSellOrdersGrandexchangeOrdersGetError>>;
}

pub struct GrandExchangeApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl GrandExchangeApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl GrandExchangeApi for GrandExchangeApiClient {
    /// Fetch the sales history of the item for the last 7 days.
    async fn get_ge_sell_history_grandexchange_history_code_get<
        'code,
        'seller,
        'buyer,
        'page,
        'size,
    >(
        &self,
        code: &'code str,
        seller: Option<&'seller str>,
        buyer: Option<&'buyer str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<
        models::DataPageGeOrderHistorySchema,
        Error<GetGeSellHistoryGrandexchangeHistoryCodeGetError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/grandexchange/history/{code}",
            local_var_configuration.base_path,
            code = crate::apis::urlencode(code)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = seller {
            local_var_req_builder =
                local_var_req_builder.query(&[("seller", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = buyer {
            local_var_req_builder =
                local_var_req_builder.query(&[("buyer", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = size {
            local_var_req_builder =
                local_var_req_builder.query(&[("size", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageGeOrderHistorySchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DataPageGeOrderHistorySchema`")))),
            }
        } else {
            let local_var_entity: Option<GetGeSellHistoryGrandexchangeHistoryCodeGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve the sell order of a item.
    async fn get_ge_sell_order_grandexchange_orders_id_get<'id>(
        &self,
        id: &'id str,
    ) -> Result<models::GeOrderReponseSchema, Error<GetGeSellOrderGrandexchangeOrdersIdGetError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/grandexchange/orders/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GeOrderReponseSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GeOrderReponseSchema`")))),
            }
        } else {
            let local_var_entity: Option<GetGeSellOrderGrandexchangeOrdersIdGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Fetch all sell orders.
    async fn get_ge_sell_orders_grandexchange_orders_get<'code, 'seller, 'page, 'size>(
        &self,
        code: Option<&'code str>,
        seller: Option<&'seller str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<models::DataPageGeOrderSchema, Error<GetGeSellOrdersGrandexchangeOrdersGetError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str =
            format!("{}/grandexchange/orders", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = code {
            local_var_req_builder =
                local_var_req_builder.query(&[("code", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = seller {
            local_var_req_builder =
                local_var_req_builder.query(&[("seller", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = size {
            local_var_req_builder =
                local_var_req_builder.query(&[("size", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageGeOrderSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DataPageGeOrderSchema`")))),
            }
        } else {
            let local_var_entity: Option<GetGeSellOrdersGrandexchangeOrdersGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`get_ge_sell_history_grandexchange_history_code_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGeSellHistoryGrandexchangeHistoryCodeGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_ge_sell_order_grandexchange_orders_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGeSellOrderGrandexchangeOrdersIdGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_ge_sell_orders_grandexchange_orders_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGeSellOrdersGrandexchangeOrdersGetError {
    UnknownValue(serde_json::Value),
}
