/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait ResourcesApi: Send + Sync {
    /// GET /resources
    ///
    /// Fetch resources details.
    async fn get_all_resources_resources_get<'min_level, 'max_level, 'skill, 'drop, 'page, 'size>(
        &self,
        min_level: Option<i32>,
        max_level: Option<i32>,
        skill: Option<models::GatheringSkill>,
        drop: Option<&'drop str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<models::DataPageResourceSchema, Error<GetAllResourcesResourcesGetError>>;

    /// GET /resources/{code}
    ///
    /// Retrieve the details of a resource.
    async fn get_resource_resources_code_get<'code>(
        &self,
        code: &'code str,
    ) -> Result<models::ResourceResponseSchema, Error<GetResourceResourcesCodeGetError>>;
}

pub struct ResourcesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ResourcesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl ResourcesApi for ResourcesApiClient {
    /// Fetch resources details.
    async fn get_all_resources_resources_get<
        'min_level,
        'max_level,
        'skill,
        'drop,
        'page,
        'size,
    >(
        &self,
        min_level: Option<i32>,
        max_level: Option<i32>,
        skill: Option<models::GatheringSkill>,
        drop: Option<&'drop str>,
        page: Option<i32>,
        size: Option<i32>,
    ) -> Result<models::DataPageResourceSchema, Error<GetAllResourcesResourcesGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/resources", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = min_level {
            local_var_req_builder =
                local_var_req_builder.query(&[("min_level", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = max_level {
            local_var_req_builder =
                local_var_req_builder.query(&[("max_level", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = skill {
            local_var_req_builder =
                local_var_req_builder.query(&[("skill", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = drop {
            local_var_req_builder =
                local_var_req_builder.query(&[("drop", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = page {
            local_var_req_builder =
                local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_str) = size {
            local_var_req_builder =
                local_var_req_builder.query(&[("size", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DataPageResourceSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DataPageResourceSchema`")))),
            }
        } else {
            let local_var_entity: Option<GetAllResourcesResourcesGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve the details of a resource.
    async fn get_resource_resources_code_get<'code>(
        &self,
        code: &'code str,
    ) -> Result<models::ResourceResponseSchema, Error<GetResourceResourcesCodeGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/resources/{code}",
            local_var_configuration.base_path,
            code = crate::apis::urlencode(code)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ResourceResponseSchema`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ResourceResponseSchema`")))),
            }
        } else {
            let local_var_entity: Option<GetResourceResourcesCodeGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`get_all_resources_resources_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllResourcesResourcesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_resource_resources_code_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetResourceResourcesCodeGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}
